// src/components/ui/DevTo/UserArticles.vue
<template>
    <!-- <div v-for="article in articles" class="w-full lg:w-4xl block bg-background mb-4" :href="article.canonical_url">
        <UserArticleContent :article_brief="article" />
    </div> -->

    <section class="bg-background w-full p-4 pt-(--header-spacing) h-svh" id="blog-posts">
        <div class="max-w-350 w-full h-full py-4">
            <WindowBook :sections="book_sections" title="Recent Posts" sidebar_heading="Log Entries"
                sidebar_class="min-w-64" @section-change="update_article()">
                <WindowCardPanel class="overflow-auto">
                    <UserArticleContent :article_brief="selected_article" should_load class="w-full">

                    </UserArticleContent>
                </WindowCardPanel>

            </WindowBook>
        </div>
    </section>
</template>
<script lang="ts" setup>
import { devto } from '@/lib/external/devto_api';
import UserArticleContent from './UserArticleContent.vue';
import WindowBook, { type WindowBookSection } from '../WindowBook.vue';
import WindowBookPage from '../WindowBookPage.vue';
import { WindowCardPanel } from '..';
import { computed, ref, watch } from 'vue';
import { useUrlSearchParams } from '@vueuse/core';

const props = defineProps<{
    username: string
}>()


const articles = await devto.articles.search(props.username)
const selected_article_index = ref(0)
const selected_article = computed(() => articles[selected_article_index.value])
const book_sections = articles.map(x => {

    const created_at = new Date(x.created_at);
    return { title: `${created_at.toLocaleDateString()} - ${x.title}`, href: `?post=${x.id}` } satisfies WindowBookSection
})

function update_article() {

    const params = new URLSearchParams(location.search)
    selected_article_index.value = Math.max(articles.findIndex(x => x.id == +params.get('post')!), 0)

}

</script>
<style></style>

// src/lib/components/UserArticles.svelte
<script lang="ts">
	import { devto, type devto as DevTo } from '$lib/external/dev_to';
	import UserArticleContent from './UserArticleContent.svelte';
	import { browser } from '$app/environment';

	let { username }: { username: string } = $props();

	let articles: DevTo.Article[] = $state([]);
	let loading = $state(true);
	let selectedArticleIndex = $state(0);

	let selectedArticle = $derived(articles[selectedArticleIndex]);

	let bookSections = $derived(
		articles.map((x) => {
			const created_at = new Date(x.created_at);
			return {
					title: `${created_at.toLocaleDateString()} - ${x.title}`,
				href: `?post=${x.id}`
			};
		})
	);

	function updateArticle() {
		if (!browser) return;
		const params = new URLSearchParams(location.search);
		const postId = Number(params.get('post'));
		selectedArticleIndex = Math.max(
			articles.findIndex((x) => x.id === postId),
			0
		);
	}

	$effect(() => {
		devto.articles.search(username).then((result) => {
			articles = result;
			loading = false;
			updateArticle();
		});
	});
</script>

<section class="bg-background w-full p-4 pt-(--header-spacing) min-h-svh" id="blog-posts">
	<div class="max-w-350 w-full h-full py-4">
		{#if loading}
			<p class="font-mono">Loading articles...</p>
		{:else}
		{JSON.stringify(bookSections)}
			<!-- WindowBook: sections={bookSections} title="Recent Posts" sidebar_heading="Log Entries" sticky_sidebar sidebar_class="min-w-64" onsection-change={updateArticle} -->
			<!-- WindowCardPanel class="overflow-auto" -->
				<UserArticleContent articleBrief={selectedArticle} shouldLoad class="w-full" />
			<!-- /WindowCardPanel -->
			<!-- /WindowBook -->
		{/if}
	</div>
</section>
